version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /bg.jpg
    destination: /var/www/html/
  - source: /partly_cloudy.png
    destination: /var/www/html/
  - source: /rain_s_cloudly.png
    destination: /var/www/html/
  - source: /script.js
    destination: /var/www/html/
  - source: /style.css
    destination: /var/www/html/
  - source: /thunderstorms.png
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root